sonar.projectKey=imsubha27_ecommerce-microservices-demo-aws
sonar.organization=imsubha27
sonar.projectName=ecommerce-microservices-demo-aws
sonar.sourceEncoding=UTF-8

sonar.sources=src,kubernetes,infrastructure,observability,scripts,protos
sonar.tests=src/cartservice/tests

sonar.exclusions=**/node_modules/**,**/bin/**,**/obj/**,**/build/**,**/.gradle/**,**/vendor/**,**/__pycache__/**,**/*.pb.go,**/*_pb2.py,**/*_pb2_grpc.py,src/**/genproto/**,src/adservice/gradle/wrapper/**,**/*.java,src/cartservice/tests/**

sonar.test.inclusions=**/*Tests.cs

sonar.coverage.exclusions=**/*_test.go,**/*Test.java,**/*Tests.cs,**/tests/**,**/test_*.py,**/*_test.py,**/Dockerfile,**/*.yml,**/*.yaml,**/*.json