sonar.projectKey=ecommerce-microservices-demo-aws
sonar.projectName=ecommerce-microservices-demo-aws
sonar.sourceEncoding=UTF-8

sonar.sources=src,kubernetes,infrastructure,observability,scripts,protos
sonar.tests=src/cartservice/tests

sonar.exclusions=**/node_modules/**,**/bin/**,**/obj/**,**/build/**,**/.gradle/**,**/vendor/**,**/__pycache__/**,**/*.pb.go,**/*_pb2.py,**/*_pb2_grpc.py,src/**/genproto/**,src/adservice/gradle/wrapper/**,**/*_test.go,**/*Test.java,**/test_*.py,**/*_test.py,src/cartservice/tests/**
sonar.test.inclusions=**/*Tests.cs
sonar.coverage.exclusions=**/*_test.go,**/*Test.java,**/*Tests.cs,**/tests/**,**/test_*.py,**/*_test.py,**/Dockerfile,**/*.yml,**/*.yaml,**/*.json

sonar.go.coverage.reportPaths=coverage/go-coverage.out
sonar.python.coverage.reportPaths=coverage/python-coverage.xml
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.cs.opencover.reportsPaths=coverage/cartservice.opencover.xml