apiVersion: apps/v1
kind: Deployment
metadata:
  name: email
  namespace: ecommerce
  labels:
    app.kubernetes.io/name: email
    app.kubernetes.io/instance: ecommerce
    app.kubernetes.io/version: "1.0"
    app.kubernetes.io/part-of: ecommerce
spec:
  serviceAccountName: ecommerce-sa
  replicas: 1
  selector:
    matchLabels:
      app: email
  template:
    metadata:
      labels:
        app: email
    spec:
      containers:
      - name: email
        image: 412628362705.dkr.ecr.us-east-1.amazonaws.com/ecommerce/emailservice:latest
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          valueFrom:
            configMapKeyRef:
              name: ecommerce-config
              key: EMAIL_PORT

      resources:
        requests:
          cpu: 100m
          memory: 64Mi
        limits:
          cpu: 200m
          memory: 128Mi
      readinessProbe:
        tcpSocket:
          port: 8080