apiVersion: apps/v1
kind: Deployment
metadata:
  name: order
  namespace: ecommerce
  labels:
    app.kubernetes.io/name: order
    app.kubernetes.io/instance: ecommerce
    app.kubernetes.io/version: "1.0"
    app.kubernetes.io/part-of: ecommerce
spec:
  serviceAccountName: ecommerce-sa
  replicas: 1
  selector:
    matchLabels:
      app: order
  template:
    metadata:
      labels:
        app: order
    spec:
      containers:
      - name: order
        image: 412628362705.dkr.ecr.us-east-1.amazonaws.com/ecommerce/orderservice:latest
        ports:
        - containerPort: 8082
        env:
        - name: PORT
          valueFrom:
            configMapKeyRef:
              name: ecommerce-config
              key: ORDER_PORT
        - name: ORDER_DB_HOST
          valueFrom:
            secretKeyRef:
              name: rds-credentials
              key: host
        - name: ORDER_DB_PORT
          valueFrom:
            configMapKeyRef:
              name: ecommerce-config
              key: ORDER_DB_PORT
        - name: ORDER_DB_NAME
          valueFrom:
            configMapKeyRef:
              name: ecommerce-config
              key: ORDER_DB_NAME
        - name: ORDER_DB_USER
          valueFrom:
            secretKeyRef:
              name: rds-credentials
              key: username
        - name: ORDER_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: rds-credentials
              key: password
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: jwt-secret

      resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 300m
            memory: 256Mi
      readinessProbe:
        httpGet:
          path: /health
          port: 8082
          initialDelaySeconds: 10
          periodSeconds: 10