apiVersion: v1
kind: Service
metadata:
  name: checkout
  namespace: ecommerce
  labels:
    app.kubernetes.io/name: checkout
    app.kubernetes.io/instance: ecommerce
    app.kubernetes.io/version: "1.0"
    app.kubernetes.io/part-of: ecommerce
spec:
  type: ClusterIP
  selector: 
    app: checkout
  ports:
    - port: 5050
      targetPort: 5050