apiVersion: apps/v1
kind: Deployment
metadata:
  name: ad
  namespace: ecommerce
  labels:
    app.kubernetes.io/name: ad
    app.kubernetes.io/instance: ecommerce
    app.kubernetes.io/version: "1.0"
    app.kubernetes.io/part-of: ecommerce
spec:
  serviceAccountName: ecommerce-sa
  replicas: 1
  selector:
    matchLabels:
      app: ad
  template:
    metadata:
      labels:
        app: ad
    spec:
      containers:
      - name: ad
        image: 412628362705.dkr.ecr.us-east-1.amazonaws.com/ecommerce/adservice:latest
        ports:
        - containerPort: 9555
        env:
        - name: PORT
          valueFrom:
            configMapKeyRef:
              name: ecommerce-config
              key: AD_PORT
        resources:
          requests:
            cpu: 100m
            memory: 200Mi
          limits:
            cpu: 300m
            memory: 400Mi
        readinessProbe:
          tcpSocket:
            port: 9555
          initialDelaySeconds: 10
          periodSeconds: 10