apiVersion: v1
kind: Service
metadata:
  name: ad
  namespace: ecommerce
  labels:
    app.kubernetes.io/name: ad
    app.kubernetes.io/instance: ecommerce
    app.kubernetes.io/version: "1.0"
    app.kubernetes.io/part-of: ecommerce
spec:
  selector:
    app: ad
  ports:
    - port: 9555
      targetPort: 9555