apiVersion: apps/v1
kind: Deployment
metadata:
  name: currency
  namespace: ecommerce
  labels:
    app.kubernetes.io/name: currency
    app.kubernetes.io/instance: ecommerce
    app.kubernetes.io/version: "1.0"
    app.kubernetes.io/part-of: ecommerce
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: currency
      app.kubernetes.io/instance: ecommerce
  template:
    metadata:
      labels:
        app.kubernetes.io/name: currency
        app.kubernetes.io/instance: ecommerce
        app.kubernetes.io/version: "1.0"
        app.kubernetes.io/part-of: ecommerce
    spec:
      serviceAccountName: ecommerce-sa
      containers:
      - name: currency
        image: 412628362705.dkr.ecr.ap-south-1.amazonaws.com/ecommerce/currencyservice:latest
        ports:
        - containerPort: 7000
        env:
        - name: PORT
          valueFrom:
            configMapKeyRef:
              name: ecommerce-config
              key: CURRENCY_PORT

        resources:
          requests:
            cpu: 100m
            memory: 64Mi
          limits:
            cpu: 200m
            memory: 128Mi
        readinessProbe:
          tcpSocket:  
            port: 7000