apiVersion: apps/v1                  # ← fix typo
kind: Deployment
metadata:
  name: redis
  namespace: ecommerce
  labels:
    app.kubernetes.io/name: redis
    app.kubernetes.io/instance: ecommerce
    app.kubernetes.io/version: "1.0"
    app.kubernetes.io/part-of: ecommerce
spec:
  replicas: 0
  selector:
    matchLabels:
      app.kubernetes.io/name: redis       
      app.kubernetes.io/instance: ecommerce
  template:
    metadata:
      labels:
        app.kubernetes.io/name: redis      
        app.kubernetes.io/instance: ecommerce
        app.kubernetes.io/version: "1.0"
        app.kubernetes.io/part-of: ecommerce
    spec:
      # NO serviceAccountName here, Redis doesn't need AWS access
      containers:
      - name: redis
        image: redis:alpine
        ports:
        - containerPort: 6379
        resources:
          requests:
            cpu: 100m
            memory: 64Mi
          limits:
            cpu: 200m
            memory: 128Mi
        readinessProbe:
          exec:
            command:
            - redis-cli
            - ping
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          exec:
            command:
            - redis-cli
            - ping
          initialDelaySeconds: 5
          periodSeconds: 10