apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: rds-credentials
  namespace: ecommerce
spec:
  refreshInterval: 15m   # how often ESO re-pulls from Secrets Manager
  secretStoreRef:
    name: aws-secrets-manager
    kind: SecretStore
  target:
    name: rds-credentials  
    creationPolicy: Owner
  data:
    - secretKey: host        # key inside the resulting K8s Secret
      remoteRef:
        key: rds-credentials   
        property: host                 
    - secretKey: username
      remoteRef:
        key: rds-credentials
        property: username
    - secretKey: password
      remoteRef:
        key: rds-credentials
        property: password

---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: app-secrets
  namespace: ecommerce
spec:
  refreshInterval: 15m
  secretStoreRef:
    name: aws-secrets-manager
    kind: SecretStore
  target:
    name: app-secrets   
    creationPolicy: Owner
  data:
    - secretKey: JWT_SECRET
      remoteRef:
        key: app-secrets
        property: JWT_SECRET
