apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - adservice/deploy.yml
  - adservice/svc.yml

  - authservice/deploy.yml
  - authservice/svc.yml

  - cartservice/deploy.yml
  - cartservice/svc.yml

  - checkoutservice/deploy.yml
  - checkoutservice/svc.yml

  - currencyservice/deploy.yml
  - currencyservice/svc.yml

  - emailservice/deploy.yml
  - emailservice/svc.yml

  - frontend/deploy.yml
  - frontend/svc.yml

  - orderservice/deploy.yml
  - orderservice/svc.yml

  - paymentservice/deploy.yml
  - paymentservice/svc.yml

  - productcatalogservice/deploy.yml
  - productcatalogservice/svc.yml

  - recommendationservice/deploy.yml
  - recommendationservice/svc.yml

  - redis/deploy.yml
  - redis/svc.yml

  - shippingservice/deploy.yml
  - shippingservice/svc.yml

  - shoppingassistantservice/deploy.yml
  - shoppingassistantservice/svc.yml