apiVersion: v1
kind: Service
metadata:
  name: auth
  namespace: ecommerce
  labels:
    app.kubernetes.io/name: auth
    app.kubernetes.io/instance: ecommerce
    app.kubernetes.io/version: "1.0"
    app.kubernetes.io/part-of: ecommerce
spec:
  type: ClusterIP
  selector: 
    app: auth
  ports:
    - port: 8081
      targetPort: 8081